#
name: Deploy

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches: ['master']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build DLL
        run: npm run build:dll

      - name: Build project
        run: npm run build

      - name: Check paths1
        run: ls /home/runner/work/

      - name: Check paths2
        run: ls /home/runner/work/resumeskool-judge-ui

      - name: Check paths3
        run: ls /home/runner/work/resumeskool-judge-ui/resumeskool-judge-ui

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist
