#
name: Deploy

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build DLL
        run: npm run build:dll

      - name: Build project
        run: npm run build

      - name: Check paths1
        run: ls /home/runner/work/

      - name: Check paths2
        run: ls /home/runner/work/resumeskool-judge-ui

      - name: Check paths3
        run: ls /home/runner/work/resumeskool-judge-ui/resumeskool-judge-ui

      - name: Upload Release asset
        uses: actions/upload-release-asset@v1
        with:
          name: production-files
          path: ./dist
